
dataset_config:
  workers: 16
  name: PartialOrOccluded
  dataname: Partial-REID
  style: partial
  part: train
  height: 384
  width: 128
  batch_size: 128
  load_img_to_cash: 1
  least_image_per_class: 4
  use_tf_sample: 1
  use_random_pad: 0

optm_config:
  name: SGD
  mode: train
  weight_decay: 0.0005
  warmup_factor: 0.
  momentum: 0.9
  epochs: 80
  start_epoch: 0
  lr: 0.05
  resume: ''

model_config:
  name: Baseline
  margin: 0.5
  alpha: 1

