dataset_config:
  workers: 16
  name: Market1501
  part: train
  height: 384
  width: 128
  batch_size: 64 # 128 是 resnest50 101
  load_img_to_cash: 1
  least_image_per_class: 4
  use_tf_sample: 0
  use_random_pad: 0
  mgn_style_aug: false

optm_config:
  name: SGD
  mode: train
  weight_decay: 0.0005
  warmup_factor: 0.
  momentum: 0.9
  epochs: 80
  start_epoch: 0
  lr: 0.025  #0.05 resnest50 101
  resume: ''

model_config:
  name: Baseline
  num_layers: resnest269 #50, 101, 101d_32x8d resnest50
  margin: 0.5
  alpha: 1

