dataset_config:
  workers: 16
  name: MaskMarket1501 #Market1501 #Occluded_Duke #Market1501 PartialOrOccluded
  part: train
  height: 384
  width: 128
  batch_size: 64 # 128 是fp32 2卡配置
  load_img_to_cash: 1
  least_image_per_class: 4
  use_tf_sample: 0
  use_random_pad: 0
  mgn_style_aug: false

optm_config:
  name: SGD
  mode: train
  weight_decay: 0.0005
  warmup_factor: 0.
  momentum: 0.9
  epochs: 80
  start_epoch: 0
  lr: 0.025  #128 0.05
  resume: ''

model_config:
  name: PGFA
  num_layers: resnet50 #50, 101, 101d_32x8d
  loss_type: ['softmax', 'triplet']
  stripe: 6
  coef: 0.9
  use_pose: false
  use_gmp: true
#  use_non_local: true

loss:
  margin: 0.5

