dataset_config:
  workers: 16
  name: Market1501
  part: train
  height: 384
  width: 128
  batch_size: 64
  load_img_to_cash: 1
  least_image_per_class: 4
  use_tf_sample: 1
  mgn_style_aug: true


optm_config:
  name: SGD
  mode: train
  weight_decay: 0.001
  warmup_factor: 0.
  momentum: 0.9
  epochs: 80
  start_epoch: 0
  lr: 0.025
  resume: ''

model_config:
  name: MGN
  margin: 0.5
  alpha: 1

