gpus: [0,1]
yaml: ../example/mgn/mgn.yaml #mgn  baseline_dist_bn   #mgn_dist_bn_multidataset
task_id: ../../snapshot/mgn/mgn_orgnize_msmt #mgn_fp16 baseline_resnet101_ibn_b128_mdmc_mix_soft_triplet   #mgn_v2_resnet_wo_ls
eval: false
convert_to_onnx: false