#gpus: [1,2]
#yaml: ../example/PartNet/market.yaml #mgn  baseline_dist_bn   #mgn_dist_bn_multidataset
#task_id: ../../snapshot/partnet/market_reid_test_8 #mgn_fp16 baseline_resnet101_ibn_b128_mdmc_mix_soft_triplet   #mgn_v2_resnet_wo_ls
gpus: [2,3]
yaml: ../example/baseline/baseline_softmax_multidataset.yaml #mgn  baseline_dist_bn   #mgn_dist_bn_multidataset PartNet
task_id: ../../snapshot/yewu/softmax_id1_0
eval: false
convert_to_onnx: false
debug: false