gpus: [2,3]
#yaml: 'experiment/occluded/bmask.yaml'
yaml: '../example/distribute/baseline_dist_bn.yaml' #mgn
task_id: '../../snapshot/distribute/baseline_b96_dist_bn_6x16' #mgn_fp16
eval: false
use_fp16: true