gpus: [2,3]
yaml: '../example/distribute/mgn_dist_bn_multidataset.yaml' #mgn  baseline_dist_bn   #mgn_dist_bn_multidataset
task_id: '../../snapshot/distribute/mgn_v2_resnet101_ibn_a' #mgn_fp16 baseline_resnet101_ibn_b128_mdmc_mix_soft_triplet   #mgn_v2_resnet_wo_ls
eval: false
with_flip: false
use_fp16: false
convert_to_onnx: false