gpus: [0,1]
#yaml: 'experiment/occluded/bmask.yaml'
yaml: '../example/distribute/baseline_dist_bn_multidataset.yaml' #mgn
task_id: '../../snapshot/distribute/baseline_b128_duke_share_bn' #mgn_fp16
eval: false
use_fp16: false