#gpus: [1,2]
#yaml: ../example/PartNet/market.yaml #mgn  baseline_dist_bn   #mgn_dist_bn_multidataset
#task_id: ../../snapshot/partnet/market_reid_test_8 #mgn_fp16 baseline_resnet101_ibn_b128_mdmc_mix_soft_triplet   #mgn_v2_resnet_wo_ls
gpus: [0,3]
yaml: ../example/VAAL/vaal_b3.yaml #mgn  baseline_dist_bn   #mgn_dist_bn_multidataset
task_id: ../../snapshot/vaal/vaal_b3_duke
eval: true
convert_to_onnx: false
debug: true